### ISSUE TITLE
Error when using template_ordered

### ISSUE THREAD

**Issue by syffer** [KristoforMaynard/SublimeAutoDocstring#25]
I tried to force the template_ordered to True, and an error occurs when converting one style to another (Numpy -> Google or Google -> Numpy) : 

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 961, in run
    default_qstyle=default_qstyle)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 856, in autodoc
    new_ds = desired_style(ds)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\docstring_styles.py", line 501, in __init__
    docstr.sections[sec_name] = make_new_sec(sec)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\docstring_styles.py", line 238, in from_section
    new_sec = cls(sec.heading)
AttributeError: 'NoneType' object has no attribute 'heading'

**Comment by KristoforMaynard** [comment]
fixed by 	d9711cc
