### ISSUE TITLE
Error when using 'Convert All' command

### ISSUE THREAD

**Issue by syffer** [KristoforMaynard/SublimeAutoDocstring#26]
I have the following error when I use the 'Convert All' command (SublimeText Build 3126) : 

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 998, in run
    default_qstyle=default_qstyle, update_only=update_only)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 767, in autodoc
    target = find_preceding_declaration(view, all_defs, region)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 98, in find_preceding_declaration
    raise NotImplementedError("Shouldn't be here?")
NotImplementedError: Shouldn't be here?

**Comment by KristoforMaynard** [comment]
This appears to be related to inserting a module-level docstring. It looks like the error comes from having a single line of whitespace as the first line in a module. Also probably related: when a module starts with multiple blank lines, the docstring doesn't appear at the top of the module.

**Comment by KristoforMaynard** [comment]
This issue is still open because too much whitespace is added around freshly inserted module-level docstrings. This behavior seems to depend how many empty lines are at the start of the module. Also, it appears the ST `view.replace(...)` does not allow inserting a docstring at cursor location 0. I'm not sure if this is a bug in my understanding of the API, or a bug in ST.

**Comment by KristoforMaynard** [comment]
fixed by @syffer in #35
