### ISSUE TITLE
error when converting with a section that shouldn't be here

### ISSUE THREAD

**Issue by syffer** [KristoforMaynard/SublimeAutoDocstring#31]
The following error is raised when converting from one to another style, and that one of the section in the already generated docstring should not exists I think : 

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 962, in run
    default_qstyle=default_qstyle)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\auto_docstring.py", line 857, in autodoc
    new_ds = desired_style(ds)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\docstring_styles.py", line 501, in __init__
    docstr.sections[sec_name] = make_new_sec(sec)
  File "C:\Users\Maxime\AppData\Roaming\Sublime Text 3\Packages\SublimeAutoDocstring\docstring_styles.py", line 238, in from_section
    new_sec = cls(sec.heading)
AttributeError: 'NoneType' object has no attribute 'heading'
```

Test cases : 
- here by applying the conversion google -> numpy, with a raise section that shouldn't be here : 
```
def test2():
	"""Summary
	
	Yields:
	    TYPE: Description
	
	Raises: 
		Exception: test

	"""
	yield 2
```

- same example but with numpy -> google : 
```
def test2():
	"""Summary
	
	Raises
	-------
	Exception
	    Description

	"""
	yield 2
```

**Comment by syffer** [comment]
corrected with #33
